/**
 * Confidence Badge
 * Shows confidence level for AI-generated content
 */

import { Badge } from '@/components/ui/badge';
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from '@/components/ui/tooltip';
import { cn } from '@/lib/utils';
import { Sparkles, HelpCircle, Shield } from 'lucide-react';

export type ConfidenceLevel = 'HIGH' | 'MEDIUM' | 'LOW';
export type SourceType = 'profile' | 'ai' | 'manual' | 'gap_answers';

interface ConfidenceBadgeProps {
  confidence?: ConfidenceLevel;
  source?: SourceType;
  className?: string;
}

const CONFIDENCE_CONFIG: Record<ConfidenceLevel, {
  label: string;
  color: string;
  description: string;
}> = {
  HIGH: {
    label: 'High',
    color: 'border-green-500 text-green-600 bg-green-500/10',
    description: 'Strongly supported by your startup data',
  },
  MEDIUM: {
    label: 'Medium',
    color: 'border-amber-500 text-amber-600 bg-amber-500/10',
    description: 'Partially inferred, may need validation',
  },
  LOW: {
    label: 'Low',
    color: 'border-red-500 text-red-600 bg-red-500/10',
    description: 'AI-generated hypothesis, needs your input',
  },
};

const SOURCE_CONFIG: Record<SourceType, {
  icon: typeof Sparkles;
  label: string;
  description: string;
}> = {
  profile: {
    icon: Shield,
    label: 'From Profile',
    description: 'Extracted from your startup profile',
  },
  ai: {
    icon: Sparkles,
    label: 'AI Generated',
    description: 'Generated by AI based on context',
  },
  manual: {
    icon: HelpCircle,
    label: 'Manual Entry',
    description: 'You entered this directly',
  },
  gap_answers: {
    icon: HelpCircle,
    label: 'Gap Answers',
    description: 'From your interview responses',
  },
};

export function ConfidenceBadge({ 
  confidence, 
  source,
  className 
}: ConfidenceBadgeProps) {
  if (!confidence && !source) return null;

  const confidenceConfig = confidence ? CONFIDENCE_CONFIG[confidence] : null;
  const sourceConfig = source ? SOURCE_CONFIG[source] : null;
  const SourceIcon = sourceConfig?.icon;

  return (
    <TooltipProvider>
      <Tooltip>
        <TooltipTrigger asChild>
          <div className={cn("inline-flex items-center gap-1", className)}>
            {confidenceConfig && (
              <Badge 
                variant="outline" 
                className={cn(
                  "text-[10px] px-1.5 py-0 h-5 font-normal",
                  confidenceConfig.color
                )}
              >
                {confidenceConfig.label}
              </Badge>
            )}
            {SourceIcon && (
              <SourceIcon className="w-3 h-3 text-muted-foreground" />
            )}
          </div>
        </TooltipTrigger>
        <TooltipContent side="top" className="max-w-[200px]">
          <div className="text-xs space-y-1">
            {confidenceConfig && (
              <p><strong>Confidence:</strong> {confidenceConfig.description}</p>
            )}
            {sourceConfig && (
              <p><strong>Source:</strong> {sourceConfig.description}</p>
            )}
          </div>
        </TooltipContent>
      </Tooltip>
    </TooltipProvider>
  );
}

/**
 * Inline confidence indicator for items in a list
 */
interface ConfidenceIndicatorProps {
  confidence?: ConfidenceLevel;
}

export function ConfidenceIndicator({ confidence }: ConfidenceIndicatorProps) {
  if (!confidence) return null;

  const config = CONFIDENCE_CONFIG[confidence];

  return (
    <span 
      className={cn(
        "inline-block w-2 h-2 rounded-full ml-2",
        confidence === 'HIGH' && "bg-green-500",
        confidence === 'MEDIUM' && "bg-amber-500",
        confidence === 'LOW' && "bg-red-500"
      )}
      title={`${config.label} confidence: ${config.description}`}
    />
  );
}
